---
author: "Equipo EDUMER"
bibliography: "../input/bib/merit-edjust.bib"
csl: "../input/bib/apa6.csl"
---

# Introduction

Since 1980, economic inequality and wealth concentration have dramatically increased worldwide, becoming one of the main challenges for the social sciences. Globally, in 2021, less than 50% of the world population owned only 2% of the wealth, while the richest 10% concentrated 76%. Futhermore, the wealthiest 1% captured nearly 38% of total assets [@chancel_world_2022]. This context of economic disparity has sparked renewed interest in studying not only the objective aspects of inequality, such as income and access to resources, but also its subjective dimensions, including perceptions, beliefs, and associated attitudes [@janmaat_subjective_2013]. Such dimensions are deemed as key to understand the political delegitimation that economic inequality can elicit [@castillo_perception_2022]. Therefore, understanding how people perceive inequality is crucial, as these perceptions can influence how societies comprehend and justify (or not) inequality in the distribution of goods and services, as well as their capacity to funnel political discontent and eventually opposition to the current economic distribution.

The justification of economic inequality has a long tradition in sociology, with seminal works such as the ones from Kluegel [-@kluegel_social_1995a; -@kluegel_beliefs_1981c] and Lane [@lane_political_1962; @lane_market_1986]. Lane's main aim was to "help explain the tenacious hold of market capitalism on the public mind" (@lane_market_1986, p.384), proposing the distinction between market and political justice. Whereas political justice refer to government actions aligned with justice principles such equality or need, market justice involves the allocation linked to earned desserts, particularly through individual contributions based on as effort and ability. Sociological survey research in this area has considered questions related to the extent to which it is considered just to get better access to social services (such as pensions, health and education) based on payment capacity. Although such services could be considered basic citizens rights, the evidence suggest that a relevant share of the population justify inequality in these domains [@lindh_public_2015]. In the present paper, we argue that there are two relevant factors to take into account when analyzing differences between individuals and groups to this regard: the perception of economic inequality, and the perception of meritocracy.

The perception of economic inequality can be understood as an individual's subjective assessment of how resources are allocated among members of a given society [@akyelken_urban_2020]. Regardless of their measurement, various studies have shown that this perception often underestimates the gap between the rich and the poor, revealing inconsistencies between objective and subjective aspects of inequality [@trump_income_2018]. Moreover, there is consistent evidence that perceived inequality, even under control of objective inequality, could have implications for attitudes toward the distribution of goods and services [@castillo_perception_2022; @schroder_income_2017]. redistributive preferences, justification of inequality, and legitimacy of the economic system [@castillo_perception_2022; @garcia-sanchez_perceptions_2018; @garcia-sanchez_attitudes_2020]. From this perspective, in this paper we argue that perceptions of economic inequality may play a relevant aspect when understanding market justice preferences, as a lower perceived inequality could reinforce the idea that the differences in access to social services could be justified --- a link that becomes difficult to hold when high inequality is perceived.

Along with perception of inequality, a second focus of this paper is the perception of meritocracy. Meritocracy posits that inequality can be legitimized through distributive criteria such as effort and talent [@young_rise_1962; @davis_principles_2001]. Previous studies have demonstrated that people with stronger meritocratic beliefs tend to perceive less inequality as they attribute economic differences to individual achievements [@mijs_paradox_2021; @wilson_role_2003] and also to justify more inequality as these beliefs are associated with attitudes that legitimize status differences [@batruch_belief_2023]. In a context as Chile, where the distribution of goods and services is predominantly governed by market logics strongly introduced during the military dictatorship (1973-1989) [@boccardo_30_2020], meritocratic perceptions have the potential to affect the acceptance of social inequalities. Therefore, incorporating the perception of meritocracy in this literature allows for an understanding of how attitudes toward inequality are shaped not only by the perception of economic gaps, but also by beliefs about how these gaps are justified. Furthermore, these beliefs are often consolidated from an early age, reinforced by institutions promoting values such as effort and individual skills to climb socially [@castillo_socialization_2024; @reynolds_perceptions_2014].

At this point we can propose the following research questions: To what extent the preferences for market justice are associated with perceptions of inequality and meritocracy? How stable are these associations (within subjects) along time? The primary objective of this study is to analyze the interplay between perceptions of inequality and meritocracy and their joint influence on preferences for market justice along time in Chile using the panel survey ELSOC (Social Chilean Longitudinal Study, 2016-2023). The chilean case appears as a particular case for studying market justice preferences given their story of high inequality and strong free-market policies introduced in the dictatorship period [@boccardo_30_2020; @flores_top_2020]. Additionally, this analysis seeks to explore how political and social contingencies---such as the 2019 and 2022 social movements---might have moderated these relationships by prompting more critical reflection on the commodification of social services. Recognizing the temporal dimension in shaping market justice preferences is essential, given that historical and contextual factors that could challenge or reaffirm the way in which individuals persceive inequality and meritocracy, and consequantely --- following our argument --- the preferences for market justice.

------------------------------------------------------------------------

Papelera

Research shows that greater perceived inequality fosters stronger preferences for redistribution, regardless of actual inequality levels [@garcia-sanchez_vicious_2019; @gimpelson_misperceiving_2018]. However, other findings suggest that heightened perceptions of income gaps between high- and low-paying occupations may lead to greater justification of inequality [@Castillo2011].

A less explored area in this regard concerns market justice, which denotes the degree to which individuals consider just that social goods and services (e.g., health, pensions, education) are allocated according to individual contribution, competition, and ability to pay [@lane_market_1986; @lindh_public_2015; @kluegel_legitimation_1999]. Market justice attitudes reflect the belief that the market promotes procedural fairness---equality of opportunity---so that outcomes result from individual achievement [@lane_market_1986]. Indeed, Lindh \[-\] shows that market justice preferences are stronger in countries with higher private spending on services than in those with more comprehensive welfare systems.

[lo de la interacción, me parece que es too much para la introducción]
The perception of meritocracy and the perception of economic inequality would interact intricately in shaping preferences for market justice. On the one hand, a stronger perception of merit as a criterion for distribution could minimize the perception of economic gaps, thus justifying an unequal system [@castillo_percepcion_2019; @mijs_paradox_2021]. On the other hand, the perception of inequality could moderate the impact of meritocracy, as a higher perception of economic gaps might challenge the idea that these are solely based on merit.