---
title: "Supplementary material"
format:
  html: 
    code-fold: true
    html-math-method: katex
    number-sections: true
  docx:
    number-sections: true
  pdf: 
    geometry: margin=0.5cm
    template-partials: 
      - title.tex
    keep-tex: true
    number-sections: true
editor: source
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
colorlinks: true
fig-height: 4
fig-width: 7.5
editor_options: 
  chunk_output_type: console
--- 
```{r}
#| echo: false
#| message: false
#| warning: false

library(knitr)
knitr::opts_chunk$set(echo = TRUE, include = TRUE, warning = FALSE, message = FALSE)

table_format <- if(is_html_output()) {
  "html"
} else if(is_latex_output()) {
  "latex"
}
table_format2 <- if(is_html_output()) {
  T
} else if(is_latex_output()) {
  F
}

options(kableExtra.html.bsTable = T)
options(knitr.kable.NA = "")
```

```{r}
#| echo: false
#| include: false


if (! require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, 
               sjmisc, 
               sjPlot, 
               lme4, 
               here, 
               performance,
               texreg, 
               ggdist,
               kableExtra,
               shadowtext,
               MetBrewer,
               patchwork,
               sjlabelled,
               summarytools)


options(scipen=999)
rm(list = ls())
```

```{r}
#| echo: false
#| include: false 

load(file = here("input/data/proc/df_study1_long_t7.RData"))

# Generate analytical sample

df_study1 <- df_study1_long_t7 %>%
  select(idencuesta,
         ola,
         ponderador_long_total,
         segmento,
         estrato,
         just_health,
         just_pension,
         just_educ,
         mjp, 
         perc_inequality, 
         merit_effort, 
         merit_talent, 
         educ,
         quintil1,
         sex,
         age,
         ess, 
         ideo) %>% 
  na.omit() %>% 
  mutate(ola = case_when(ola == 1 ~ 1,
                         ola == 2 ~ 2, 
                         ola == 3 ~ 3,
                         ola == 4 ~ 4,
                         ola == 6 ~ 5,
                         ola == 7 ~ 6)) %>% 
  mutate(ola = as.factor(ola),
         ola_num = as.numeric(ola),
         ola_2=as.numeric(ola)^2)

df_study1 <- df_study1 %>%
  group_by(idencuesta) %>%             # Agrupar por el identificador del participante
  mutate(n_participaciones = n()) %>%  # Contar el número de filas (participaciones) por participante
  ungroup()

df_study1 <- df_study1 %>% filter(n_participaciones>1)

# Corregir etiquetas

df_study1$just_health <- sjlabelled::set_label(df_study1$just_health, 
                        label = "Health distributive justice")

df_study1$just_pension <- sjlabelled::set_label(df_study1$just_pension, 
                        label = "Pension distributive justice")

df_study1$just_educ <- sjlabelled::set_label(df_study1$just_educ, 
                        label = "Education distributive justice")

df_study1$merit_effort <- sjlabelled::set_label(df_study1$merit_effort, 
                        label = "People are rewarded for their efforts")

df_study1$merit_talent <- sjlabelled::set_label(df_study1$merit_talent, 
                        label = "People are rewarded for their intelligence")

```



```{r, echo=FALSE, include=FALSE}

df_study1$merit_effort <- as_numeric(df_study1$merit_effort)
df_study1$merit_talent <- as_numeric(df_study1$merit_talent)

df_study1 <- df_study1 %>% 
  mutate(ola = case_when(ola == 1 ~ "2016",
                         ola == 2 ~ "2017",
                         ola == 3 ~ "2018",
                         ola == 4 ~ "2019",
                         ola == 5 ~ "2022",
                         ola == 6 ~ "2023"),
         ola = factor(ola, levels = c("2016",
                                        "2017",
                                        "2018",
                                        "2019",
                                        "2022",
                                        "2023")))


df_study1 <- df_study1 %>% 
  group_by(idencuesta) %>% 
  mutate(perc_inequality_mean = mean(perc_inequality, na.rm = T),
         perc_inequality_cwc = perc_inequality - perc_inequality_mean,
         merit_effort_mean = mean(merit_effort, na.rm = T),
         merit_effort_cwc = merit_effort - merit_effort_mean,
         merit_talent_mean = mean(merit_talent, na.rm = T),
         merit_talent_cwc = merit_talent - merit_talent_mean,
         ) %>% 
  ungroup()
```


```{r}
#| label: tbl-summary-controls
#| tbl-cap: "Descriptive statistics for control variables for the first wave (2016)"
#| tbl-cap-location: top
#| results: asis
#| echo: false

t2 <- df_study1 %>% 
  filter(ola == "2016") %>% 
  select(educ,
         quintil1,
         sex,
         age,
         ess, 
         ideo) 

t2$educ <- sjlabelled::set_label(t2$educ, "Educational level")
t2$quintil1 <- sjlabelled::set_label(t2$quintil1, "Household income quintile (per capita)")
t2$sex <- sjlabelled::set_label(t2$sex, "Sex")
t2$age <- sjlabelled::set_label(t2$age, "Age")
t2$ess <- sjlabelled::set_label(t2$ess, "Subjective social status")
t2$ideo <- sjlabelled::set_label(t2$ideo, "Political identification")


df<-dfSummary(t2,
               plain.ascii = FALSE,
               style = "multiline",
               tmp.img.dir = "/tmp",
               graph.magnif = 0.75,
               headings = F,  # encabezado
               varnumbers = F, # num variable
               labels.col = T, # etiquetas
               na.col = F,    # missing
               graph.col = F, # plot
               valid.col = T, # n valido
               col.widths = c(30,10,10,10))

df$Variable <- NULL # delete variable column

print(df)
```


```{r}
#| label: fig-matrix
#| out-width: '90%'
#| fig-asp: 1
#| fig-cap: "Correlation matrix of the main variables for the last wave (2023)"
#| fig-cap-location: top
#| echo: false
#| results: asis


M <- df_study1 %>%
  filter(ola == "2016") %>% 
  select(mjp, perc_inequality, merit_effort, merit_talent) %>% 
  mutate_all(.funs = ~ as.numeric(.)) %>% 
  cor(use = "pairwise.complete.obs", method = "pearson")

diag(M) <- NA

rownames(M) <- c("A. Marjet justice preferences",
                 "B. Inequality gap perception",
                 "C. People are rewarded for their efforts ",
                 "D. People are rewarded for their intelligence")

#set Column names of the matrix
colnames(M) <-c("(A)", "(B)","(C)","(D)")

#Plot the matrix using corrplot
corrplot::corrplot(M,
                   method = "color",
                   addCoef.col = "black",
                   type = "upper",
                   tl.col = "black",
                   col = colorRampPalette(c("#E16462", "white", "#0D0887"))(12),
                   bg = "white",
                   na.label = "-") 

```




```{r}
#| echo: false
#| include: false 

m0 <- lmer(mjp ~ 1 + (1 | idencuesta), 
                data = df_study1, weights = ponderador_long_total)

performance::icc(m0, by_group = T)

df_study1 <- df_study1 %>%
  mutate(
    perc_inequality_cwc_dic = ifelse(perc_inequality_cwc > mean(perc_inequality_cwc, na.rm = TRUE), "mayor", "menor"),
    merit_effort_cwc_dic = ifelse(merit_effort_cwc > mean(merit_effort_cwc, na.rm = TRUE), "mayor", "menor"),
    merit_talent_cwc_dic = ifelse(merit_talent_cwc > mean(merit_talent_cwc, na.rm = TRUE), "mayor", "menor"),
    perc_inequality_mean_dic = ifelse(perc_inequality_mean > mean(perc_inequality_mean, na.rm = TRUE), "mayor", "menor"),
    merit_effort_mean_dic = ifelse(merit_effort_mean > mean(merit_effort_mean, na.rm = TRUE), "mayor", "menor"),
    merit_talent_mean_dic = ifelse(merit_talent_mean > mean(merit_talent_mean, na.rm = TRUE), "mayor", "menor")
  ) %>%
  mutate(across(ends_with("_dic"), factor, levels = c("menor", "mayor")))

## WE and BE

m1 <- lmer(mjp ~ 1 + ola + (1 | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m1.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + (1 | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m2 <- lmer(mjp ~ 1 + ola_num + ola_2 + (1 + ola_num | idencuesta),
                data = df_study1, weights = ponderador_long_total)

anova(m1.1, m2)

m3 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + (1 + ola_num | idencuesta), 
           data = df_study1, weights = ponderador_long_total)

m4 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + (1 + ola_num | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m5 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean +  (1 + ola_num | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m6 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean +  merit_effort_mean + merit_talent_mean + (1 + ola_num | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m7 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + ola_num | idencuesta),
                data = df_study1, weights = ponderador_long_total)


# interactions 
m8 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_effort_cwc_dic*perc_inequality_cwc_dic + merit_talent_cwc*perc_inequality_cwc +
              (1 + merit_effort_cwc + merit_talent_cwc + perc_inequality_cwc | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m8.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_effort_cwc*perc_inequality_cwc +
              (1 + merit_effort_cwc + perc_inequality_cwc | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m8.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_talent_cwc*perc_inequality_cwc +
              (1 + merit_talent_cwc + perc_inequality_cwc | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m9 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_effort_mean*perc_inequality_mean + merit_talent_mean*perc_inequality_mean +
              (1 | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m9.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_effort_mean*perc_inequality_mean +
              (1 | idencuesta),
                data = df_study1, weights = ponderador_long_total)

m9.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_talent_mean*perc_inequality_mean +
              (1 | idencuesta),
                data = df_study1, weights = ponderador_long_total)

# growth curves

m10 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality*ola_num + merit_effort + merit_talent + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + perc_inequality + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m10.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc*ola_num + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + perc_inequality_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m10.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean*ola_num + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + perc_inequality_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)


m11 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality + merit_effort*ola_num  + merit_talent + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + merit_effort + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m11.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc*ola_num  + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + merit_effort_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m11.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc  + merit_talent_cwc + perc_inequality_mean + merit_effort_mean*ola_num + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + merit_effort_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m12 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort + merit_talent*ola_num + perc_inequality_mean +  merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              (1 + merit_talent + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m12.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc*ola_num + perc_inequality_mean +  merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              (1 + merit_talent_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m12.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean +  merit_effort_mean + merit_talent_mean*ola_num + educ + quintil1 + ess + ideo + sex + age + 
              (1 + merit_talent_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m13 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality  + merit_effort + merit_talent + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_effort*perc_inequality*ola_num +
              (1 + perc_inequality + merit_effort  + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m13.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc  + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_effort_cwc*perc_inequality_cwc*ola_num +
              (1 + perc_inequality_cwc + merit_effort_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m13.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc  + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             ola_num*merit_effort_mean*perc_inequality_mean +
              (1 + perc_inequality_mean + merit_effort_mean  + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m14 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality +  merit_effort + merit_talent + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              merit_talent*perc_inequality*ola_num +
              (1 + perc_inequality + merit_talent + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m14.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              merit_talent_cwc*perc_inequality_cwc*ola_num +
              (1 + perc_inequality_cwc + merit_talent_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m14.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              merit_talent_mean*perc_inequality_mean*ola_num +
              (1 + perc_inequality_mean + merit_talent_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 



#knitreg(list(m13.1, m13.2,m14.1, m14.2))
```


```{r echo=FALSE, results='asis'}
ccoef <- list(
  "(Intercept)" = "Intercept",
  "ola2017" = "Wave 2017",
  "ola2018" = "Wave 2018",
  "ola2019" = "Wave 2019",
  "ola2022" = "Wave 2022",
  "ola2023" = "Wave 2023",
  ola_num = "Wave",
  ola_2 = "Wave^2",
  perc_inequality_cwc = "Perception inequality (WE)",
  merit_effort_cwc = "Merit: Effort (WE)",
  merit_talent_cwc = "Merit: Talent (WE)",
  perc_inequality_mean = "Perception inequality (BE)",
  merit_effort_mean = "Merit: Effort (BE)",
  merit_talent_mean = "Merit: Talent (BE)",
  "educUniversitary" = "Universitary education (Ref.= Less than Universitary)",
  quintil1Q2 = "Quintile Q2",
  quintil1Q3 = "Quintile Q3",
  quintil1Q4 = "Quintile Q4",
  quintil1Q5 = "Quintile Q5",
  quintil1QNA = "Quintile no information",
  ess = "Subjective social status",
  ideoCenter = "Center",
  ideoRight = "Right",
  "ideoDoes not identify" = "Does not identify",
  sexFemale = "Female (Ref.= Male)",
  "age30-49" = "Age 30-49",
  "age50-64" = "Age 50-64",
  "age65 or more" = "Age 65 or more"
  )

texreg::texreg(list(m0, m1, m2, m3, m4, m5, m6, m7),
               custom.model.names = c("Model 0",paste0("Model ", seq(1:7))),
               caption = "Complete longitudinal multilevel models for market justice preferences",
               caption.above = T,
               stars = c(0.05, 0.01, 0.001),
               custom.coef.map = ccoef,
               digits = 3,
               groups = list("Wave (Ref.= 2016)" = 2:6,
                             "Income quintile (Ref.= Quintile 1)" = 16:20,
                             "Political identification (Ref.= Left)" = 22:24,
                             "Age (Ref.= 18-29)" = 26:28),
               custom.note = "Note: Cells contain regression coefficients with standard errors in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.5,
               include.loglik = FALSE,
               include.aic = FALSE,
               center = T,
               custom.gof.names = c("BIC", "Numb. obs.", "Num. groups: individuals", "Var: individuals (Intercept)", "Var: Residual", "Var: individuals, wave", "Cov: individuals (Intercept), wave"))
              
```



```{r}
#| echo: false
#| include: false 

# growth curves con ola categorica

m15.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc*ola + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + perc_inequality_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m15.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean*ola + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + perc_inequality_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)


m16.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc*ola  + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + merit_effort_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m16.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc + merit_effort_cwc  + merit_talent_cwc + perc_inequality_mean + merit_effort_mean*ola + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + (1 + merit_effort_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 


m17.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc*ola + perc_inequality_mean +  merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              (1 + merit_talent_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m17.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean +  merit_effort_mean + merit_talent_mean*ola + educ + quintil1 + ess + ideo + sex + age + 
              (1 + merit_talent_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 


m18.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc  + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             merit_effort_cwc*perc_inequality_cwc*ola +
              (1 + perc_inequality_cwc + merit_effort_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)

m18.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc  + merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
             ola*merit_effort_mean*perc_inequality_mean +
              (1 + perc_inequality_mean + merit_effort_mean  + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total)


m19.1 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              merit_talent_cwc*perc_inequality_cwc*ola +
              (1 + perc_inequality_cwc + merit_talent_cwc + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

m19.2 <- lmer(mjp ~ 1 + ola_num + ola_2 + perc_inequality_cwc +  merit_effort_cwc + merit_talent_cwc + perc_inequality_mean + merit_effort_mean + merit_talent_mean + educ + quintil1 + ess + ideo + sex + age + 
              merit_talent_mean*perc_inequality_mean*ola +
              (1 + perc_inequality_mean + merit_talent_mean + ola_num| idencuesta),
                data = df_study1, weights = ponderador_long_total) 

```



```{r echo=FALSE, results='asis'}
#| label: tbl-interactions_olacateg
#| tbl-cap: "Interactions for meritocracy, perceived economic inequality and market justice preferences"
#| tbl-cap-location: top

ccoef <- list(
  "(Intercept)" = "Intercept",
  "perc_inequality_cwc:ola2017" = "Wave 2017 x Perception inequality (WE)",
  "perc_inequality_cwc:ola2018" = "Wave 2018 x Perception inequality (WE)",
  "perc_inequality_cwc:ola2019" = "Wave 2019 x Perception inequality (WE)",
  "perc_inequality_cwc:ola2022" = "Wave 2022 x Perception inequality (WE)",
  "perc_inequality_cwc:ola2023" = "Wave 2023 x Perception inequality (WE)",
  
  "merit_effort_cwc:ola2017" = "Wave 2017 x Merit: effort (WE)",
  "merit_effort_cwc:ola2018" = "Wave 2018 x Merit: effort (WE)",
  "merit_effort_cwc:ola2019" = "Wave 2019 x Merit: effort (WE)",
  "merit_effort_cwc:ola2022" = "Wave 2022 x Merit: effort (WE)",
  "merit_effort_cwc:ola2023" = "Wave 2023 x Merit: effort (WE)",

  "merit_talent_cwc:ola2017" = "Wave 2017 x Merit: talent (WE)",
  "merit_talent_cwc:ola2018" = "Wave 2018 x Merit: talent (WE)",
  "merit_talent_cwc:ola2019" = "Wave 2019 x Merit: talent (WE)",
  "merit_talent_cwc:ola2022" = "Wave 2022 x Merit: talent (WE)",
  "merit_talent_cwc:ola2023" = "Wave 2023 x Merit: talent (WE)",
  
  "perc_inequality_mean:ola2017" = "Wave 2017 x Perception inequality (BE)",
  "perc_inequality_mean:ola2018" = "Wave 2018 x Perception inequality (BE)",
  "perc_inequality_mean:ola2019" = "Wave 2019 x Perception inequality (BE)",
  "perc_inequality_mean:ola2022" = "Wave 2022 x Perception inequality (BE)",
  "perc_inequality_mean:ola2023" = "Wave 2023 x Perception inequality (BE)",
  
  
  "merit_effort_mean:ola2017" = "Wave 2017 x Merit: effort (BE)",
  "merit_effort_mean:ola2018" = "Wave 2018 x Merit: effort (BE)",
  "merit_effort_mean:ola2019" = "Wave 2019 x Merit: effort (BE)",
  "merit_effort_mean:ola2022" = "Wave 2022 x Merit: effort (BE)",
  "merit_effort_mean:ola2023" = "Wave 2023 x Merit: effort (BE)",
  
   "merit_talent_mean:ola2017" = "Wave 2017 x Merit: talent (BE)",
  "merit_talent_mean:ola2018" = "Wave 2018 x Merit: talent (BE)",
  "merit_talent_mean:ola2019" = "Wave 2019 x Merit: talent (BE)",
  "merit_talent_mean:ola2022" = "Wave 2022 x Merit: talent (BE)",
  "merit_talent_mean:ola2023" = "Wave 2023 x Merit: talent (BE)"
  
    )

texreg::texreg(list(m15.1, m16.1, m17.1, m15.2, m16.2, m17.2),
               custom.model.names = c("Model 18", "Model 19", "Model 20", "Model 21", "Model 22", "Model 23"),
               caption = NULL,
               stars = c(0.05, 0.01, 0.001),
               custom.coef.map = ccoef,
               digits = 3,
               caption.above = T,
               custom.note = "Note: Cells contain regression coefficients with standard errors in parentheses. %stars. CWC = centered within group.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.5,
               include.loglik = FALSE,
               include.aic = FALSE,
               center = T,
               custom.gof.rows = list("Controls"=c(rep("Yes",6))))




```

