---
title: "Perceptions of Inequality and Meritocracy: Their Interplay in Shaping Preferences for Market Justice in Chile (2016-2023)"
format:
  html: 
    code-fold: true
    html-math-method: katex
    number-sections: true
  docx:
    number-sections: true
  pdf: 
    geometry: margin=2cm
    template-partials: 
      - title.tex
    keep-tex: true
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
    number-sections: true
editor: source
bibliography: "../input/bib/merit-edjust.bib"
# csl: "input/bib/apa6.csl"
csl: "../input/bib/harvard.csl"
author:
  - name: Juan Carlos Castillo
    corresponding: true
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
      - ref: 2
      - ref: 3
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: alaffertt@estudiante.uc.cl 
    affiliations:
      - ref: 4
  - name: Kevin Carrasco
    orcid: 0000-0002-9348-8361
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 2
  - name: Julio Iturra-Sanhueza
    orcid: 0000-0003-1993-3479
    email: julioiturrasanhueza@gmail.com 
    affiliations:
      - ref: 5     
affiliations: 
  - id: 1
    name: Departamento de Sociología, Universidad de Chile
  - id: 2
    name: Centro de estudios del conflicto y cohesión social (COES)
  - id: 3
    name: Núcleo milenio de desigualdades y oportunidades digitales (NUDOS)
  - id: 4
    name: Instituto de Sociología, Pontificia Universidad Católica de Chile
  - id: 5
    name: International Graduate School of Social Sciencies (BIGSSS), University of Bremen, Germany
citeproc: true
abstract: | 
 Several countries have experienced a shift towards an increasing commodification and private provision of public policies, in areas such as health, education, and pensions. In Latin America, Chile stands out as a paradigmatic case of privatizations, which were strongly introduced during the military dictatorship (1973-1989), and maintained after the return of democracy. From a moral economy perspective, such institutional design has had deeply cultural consequences in terms of attitudes, ideologies and preferences towards market mechanisms. Within this framework, the present study delves into the relationship between perceptions of economic inequality, meritocratic beliefs, and market justice preferences in Chile between 2016 and 2023. Using six waves of panel data from the Chilean Longitudinal Social Survey – ELSOC (N=1,687; 8,643 observations along time), we assess whether a lower inequality perception and a higher meritocratic perception increases the preferences for private provision in health, education and pensions. The findings support the role of inequality perception, whereas the role of merit perceptions are not as straightforward. These findings contribute to a deeper understanding of how distributive beliefs evolve in contexts marked by persistent inequality and entrenched neoliberal frameworks.
  \newline
  **Keywords**: Economic inequality, meritocracy, market justice, Chile, public preferences, inequality perception
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
colorlinks: true
fig-height: 4
fig-width: 7.5
---

```{r setup, include=FALSE}
 knitr::opts_chunk$set(echo=FALSE, warning = FALSE,message = FALSE, cache = TRUE,out.width = '85%',fig.pos= "H"
                       # , fig.align = 'center'
                       )
 # knitr::opts_knit$set(base.url = "../") #relative path for .html output file
 # knitr::opts_knit$set(root.dir = "../") #relative path for chunks within .rmd files
 options(scipen=999)
 options(kableExtra.auto_format = FALSE)
 rm(list=ls())
 options(knitr.kable.NA = '')
 options(knitr.graphics.error = FALSE)
 Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```

```{r}
# This document was last modified at {{< modified >}}
# 
# and it was last rendered at {{< now >}}

```


{{< include 01-introduction.qmd >}}

{{< include 02-antecedents.qmd >}}

{{< include 03-methods.qmd >}}

{{< include 04-analisis.qmd >}}

{{< include 05-discussion.qmd >}}

{{< include 06-conclusion.qmd >}}

# References

::: {#refs}
:::
